// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI6puQOlKccWbEQxGu3P2FyPD58FkzE4M',
    appId: '1:846328108062:web:e235d516ce54f739df0a0f',
    messagingSenderId: '846328108062',
    projectId: 'flutter-chat-app-bb4ed',
    authDomain: 'flutter-chat-app-bb4ed.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bb4ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEsXCndUhRjQftsI8wMxb2zHFx4Fxidq8',
    appId: '1:846328108062:android:e09e30290b429ff3df0a0f',
    messagingSenderId: '846328108062',
    projectId: 'flutter-chat-app-bb4ed',
    storageBucket: 'flutter-chat-app-bb4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4vV20CY9qrneCj_FErZ8YoO_yMiQc6c',
    appId: '1:846328108062:ios:02c12f163f9abff2df0a0f',
    messagingSenderId: '846328108062',
    projectId: 'flutter-chat-app-bb4ed',
    storageBucket: 'flutter-chat-app-bb4ed.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4vV20CY9qrneCj_FErZ8YoO_yMiQc6c',
    appId: '1:846328108062:ios:5ab60bab0f8c6e56df0a0f',
    messagingSenderId: '846328108062',
    projectId: 'flutter-chat-app-bb4ed',
    storageBucket: 'flutter-chat-app-bb4ed.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
